# Generated by Django 4.1 on 2022-10-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRegistro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
    ]
