# Generated by Django 4.1 on 2022-10-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppRegistro', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
